--Q7. Do low-spending customers churn more?
--•	Churn rate by spending tier
--•	Revenue contribution by churn status

-- Churn rate by spending tier
SELECT 
	CASE 
		WHEN "Lifetime_Value" >= 0 AND "Lifetime_Value" <= 1000 THEN 'low_spend'
		WHEN "Lifetime_Value" > 1000 AND "Lifetime_Value" <= 2500 THEN 'medium_spend'
		WHEN "Lifetime_Value" > 2500 THEN 'high_spend'
	END AS spending_tier,
	COUNT(*) AS total_customers,
	SUM(CASE WHEN "Churned" = 1 THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN "Churned" = 1 THEN 1.0 ELSE 0.0 END) / COUNT(*), 4) AS churn_rate
FROM ecommerce_customer_churn_cleaned
GROUP BY spending_tier
ORDER BY churn_rate DESC;

--Yes, data shows an interesting pattern: low-spending customers do have a higher churn rate (~35%), but surprisingly, so do absolute highest-spending customers (~35%). The lowest churn is in the middle tier (~22.9%).

-- Revenue contribution by churn status
WITH total_revenue AS (
    SELECT SUM("Lifetime_Value") AS grand_total
    FROM ecommerce_customer_churn_cleaned
)
SELECT 
    c."Churned",
    COUNT(*) AS customer_count,
    ROUND(SUM(c."Lifetime_Value")::numeric, 2) AS total_revenue_contribution,
    ROUND((SUM(c."Lifetime_Value") / t.grand_total * 100)::numeric, 2) AS percent_of_total_revenue
FROM ecommerce_customer_churn_cleaned c
CROSS JOIN total_revenue t
GROUP BY c."Churned", t.grand_total
ORDER BY c."Churned";
--This shows how much total revenue was generated by active vs. churned customers. Your active customers account for about 71.4% of total lifetime value, while churned customers take about 28.6% of historical revenue with them.